#!/usr/bin/env bash
set -euo pipefail

REPO_OVERLAY="fix/canvas-n11-5-v2.2-rc8-compatibility"
REPO_RENDERER="fix/canvas-n11-5-v2.2-rc8-renderer-root"
NOTE=".agents/notes/implemented/architecture/2026-08-22-canvas-v2-2-rc8-compatibility-boundary.md"
NOTE_ZH=".agents/notes/implemented/architecture/2026-08-22-canvas-v2-2-rc8-compatibility-boundary.zh.md"
PAIR=".agents/notes/implemented/architecture/2026-08-22-canvas-v2-2-rc8-compatibility-boundary.i18n.yaml"

merge_stage() {
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git fetch origin "$REPO_OVERLAY" "$REPO_RENDERER"

  set +e
  git merge --no-commit --no-edit "origin/$REPO_OVERLAY"
  merge_status=$?
  set -e
  if [ "$merge_status" -eq 0 ]; then
    echo "Expected the known three-document conflict set, but ordinary merge had no conflict."
    exit 1
  fi

  mapfile -t conflicts < <(git diff --name-only --diff-filter=U | sort)
  expected=(
    "$PAIR"
    "$NOTE"
    "$NOTE_ZH"
  )
  mapfile -t expected_sorted < <(printf '%s\n' "${expected[@]}" | sort)
  if [ "${conflicts[*]}" != "${expected_sorted[*]}" ]; then
    echo "Unexpected conflict set:"
    printf '  %s\n' "${conflicts[@]}"
    exit 1
  fi

  git checkout --ours -- "$NOTE" "$NOTE_ZH"
  git checkout --theirs -- "$PAIR"

  python - <<'PY'
from pathlib import Path

en_path = Path('.agents/notes/implemented/architecture/2026-08-22-canvas-v2-2-rc8-compatibility-boundary.md')
en = en_path.read_text()
en = en.replace(
    '# Canvas V2.2 — rc.8 compatibility is not the same as an rc.8 repository sync\n\nEnglish |',
    '# Agent Note: Canvas V2.2 rc.8 compatibility boundary\n\nStatus: implemented\n\nEnglish |',
    1,
)
problem = '''## Problem

Canvas can obey a newer Harness client contract while the private repository is still not mechanically synchronized to that release. Conflating those states would let downstream nodes treat adapters, historical sync ancestry, or one repaired ownership seam as proof of a release-wide runtime baseline.

The validated compatibility overlay now sits on the final N11 editor baseline. This renderer-root remediation also closes two concrete rc.8 ownership gaps: dynamic `ui-renderer` owns the React application root, and the Web kernel consumes the rc.8-style `window.__ModuleLoader__` queue/create facade. Those improvements are real, but release-wide version/package/build/lock/generated reconciliation and exact-head REAL assembled boot evidence are still incomplete. N11.5 therefore remains `BLOCKED / REVIEW` until the upstream-sync ledger is complete.

'''
decision_prefix = '''## Decision

Maintain two independent engineering states for Harness upgrades:

1. **Compatibility overlay** — newer public APIs, plugin seams, lifecycle rules, and Canvas authority boundaries already obeyed by the private product stack.
2. **Repository upstream sync** — official package, version, root-owner, bootstrap, build, lock/generated, and runtime-composition changes mechanically present and validated in the private tree.

The renderer/root and module-bootstrap remediation advances the second ledger but does not by itself complete it. Historical `sync/*` ancestry and green Canvas-local tests remain evidence inputs rather than release-completion proof.

'''
if '## Decision\n\n' not in en:
    raise SystemExit('English note no longer has expected Decision anchor')
en = en.replace('## Decision\n\n', problem + decision_prefix, 1)
en += '''
## Alternatives considered

**Treat the now-correct renderer/root and module bootstrap as proof of a complete rc.8 sync.** Rejected because root ownership is only one release boundary. Root/private version metadata, the complete package/version family, build external partition, lock/generated reconciliation, and REAL assembled boot evidence remain separate completion gates.

**Keep the #41 business facts but discard the validated #40 compatibility-overlay boundary.** Rejected because the renderer remediation is stacked on that overlay and must preserve its Host-authoritative Canvas contracts, `shell.main` composition, versioned catalog DTO, and plugin lifecycle semantics.

**Resolve the documentation conflict by choosing either merge side wholesale.** Rejected because #40 owns the current Agent Note format and validated overlay evidence while #41 owns newer renderer/bootstrap facts. A semantic merge is required to preserve both truths.

**Hand-edit pairing hashes.** Rejected. The bilingual consistency record is regenerated by the repository's `verify-translation-pairing --write` tool after both sides are updated.

## Consequences

The merged boundary now accurately records three distinct facts at once: the Canvas overlay is validated on final N11, renderer/root and module-bootstrap ownership are remediated, and N11.5 as a release baseline is still blocked by broader rc.8 reconciliation and REAL-composition evidence.

This preserves strict predecessor discipline for later work. #41 can be validated as the next N11.5 remediation layer without prematurely authorizing N12 to consume rc.8 as accepted. It also means future release-sync work must remove blockers only when their exact mechanical and runtime evidence exists, rather than by changing status prose.
'''
en_path.write_text(en)

zh_path = Path('.agents/notes/implemented/architecture/2026-08-22-canvas-v2-2-rc8-compatibility-boundary.zh.md')
zh = zh_path.read_text()
zh = zh.replace(
    '# Canvas V2.2 — rc.8 Compatibility 不等于仓库已完成 rc.8 同步\n\n[English]',
    '# Agent Note: Canvas V2.2 rc.8 兼容性边界\n\nStatus: implemented\n\n[English]',
    1,
)
problem_zh = '''## 问题

Canvas 可以遵守新版 Harness Client Contract，但私有仓库仍可能没有机械完整同步到该 Release。若把两者混为一谈，后续节点就可能把 Adapter、历史 sync ancestry 或单个已修复 Ownership Seam 错当成 Release-wide Runtime Baseline 的完成证明。

当前已验证的 Compatibility Overlay 已经叠在最终 N11 Editor 基线上；本 renderer-root remediation 还修复了两个明确的 rc.8 Ownership 缺口：动态 `ui-renderer` 接管 React Application Root，Web Kernel 改为消费 rc.8 风格的 `window.__ModuleLoader__` queue/create facade。这些改进是真实的，但 Release-wide Version/Package/Build/Lock/Generated Reconciliation 与 exact-head REAL assembled boot evidence 仍未闭环。因此 N11.5 继续保持 `BLOCKED / REVIEW`。

'''
decision_zh = '''## 决策

Harness Upgrade 必须维护两个相互独立的工程状态：

1. **Compatibility Overlay** — 私有产品栈已经遵守哪些新版 Public API、Plugin Seam、Lifecycle Rule 与 Canvas Authority Boundary。
2. **Repository Upstream Sync** — 哪些 Official Package、Version、Root-owner、Bootstrap、Build、Lock/Generated 与 Runtime-composition Change 已机械进入私有树并获得验证。

Renderer/Root 与 Module-bootstrap Remediation 会推进第二套 Ledger，但不会单独完成它。历史 `sync/*` ancestry 与绿色 Canvas-local Test 仍只是 Evidence Input，不是 Release Completion Proof。

'''
if '## 决策\n\n' not in zh:
    raise SystemExit('Chinese note no longer has expected Decision anchor')
zh = zh.replace('## 决策\n\n', problem_zh + decision_zh, 1)
zh += '''
## 备选方案

**把已经正确的 Renderer/Root 与 Module Bootstrap 当成完整 rc.8 Sync 证明。** 拒绝，因为 Root Ownership 只是 Release Boundary 的一部分；Root/Private Version Metadata、完整 Package/Version Family、Build External Partition、Lock/Generated Reconciliation 与 REAL assembled boot evidence 仍是独立完成门槛。

**保留 #41 的新业务事实，但丢弃已验证的 #40 Compatibility Overlay Boundary。** 拒绝，因为 Renderer Remediation 正是叠在该 Overlay 上，必须继续保留 Host-authoritative Canvas Contract、`shell.main` Composition、Versioned Catalog DTO 与 Plugin Lifecycle Semantics。

**文档冲突直接整边选择 ours 或 theirs。** 拒绝，因为 #40 持有当前 Agent Note 规范格式和已验证 Overlay Evidence，#41 持有更新的 Renderer/Bootstrap Facts；只有语义合并才能同时保留两边真实信息。

**手工填写 pairing hash。** 拒绝。双语一致性记录由仓库 `verify-translation-pairing --write` 工具在两侧同步后重新生成。

## 后果

合并后的边界同时准确记录三件事：Canvas Overlay 已在最终 N11 上验证；Renderer/Root 与 Module-bootstrap Ownership 已修复；N11.5 作为 Release Baseline 仍被更大范围 rc.8 Reconciliation 与 REAL-composition Evidence 阻塞。

这样可以继续保持严格的 predecessor discipline：#41 可以作为 N11.5 下一层 Remediation 接受独立验证，但不能因此提前授权 N12 把 rc.8 当作 accepted baseline。后续 Release-sync 工作也只能在对应 Mechanical/Runtime Evidence 真正存在时移除 Blocker，而不能靠修改状态文字完成验收。
'''
zh_path.write_text(zh)
PY

  git add -- "$NOTE" "$NOTE_ZH" "$PAIR"
  test -z "$(git diff --name-only --diff-filter=U)"
  grep -Fq '# Agent Note: Canvas V2.2 rc.8 compatibility boundary' "$NOTE"
  grep -Fq 'Status: implemented' "$NOTE"
  grep -Fq '## Problem' "$NOTE"
  grep -Fq '## Alternatives considered' "$NOTE"
  grep -Fq '## Consequences' "$NOTE"
  grep -Fq 'uiRenderer.mount(container)' "$NOTE"
  grep -Fq '__ModuleLoader__' "$NOTE"
  echo "Exact three-file semantic conflict resolution staged: PASS"
}

install_stage() {
  set -o pipefail
  pnpm install --frozen-lockfile >/tmp/install.log 2>&1 || { tail -n 260 /tmp/install.log; exit 1; }
  echo "N11.5 renderer-root frozen workspace install: PASS"
}

pair_commit_stage() {
  pnpm run verify-translation-pairing --write "$NOTE"
  git add -- "$NOTE" "$NOTE_ZH" "$PAIR"
  git commit -m "merge(canvas): stack N11.5 renderer root on validated overlay"
  git merge-base --is-ancestor "origin/$REPO_OVERLAY" HEAD
  test -z "$(git ls-files -u)"
  echo "Renderer-root real predecessor merge commit: PASS"
}

ownership_stage() {
  test -f packages/client/ui-renderer/package.json
  grep -R -Fq "createRoot" packages/client/ui-renderer/src/client
  grep -Fq "uiRenderer.mount" packages/client/web/src/boot.ts
  grep -R -Fq "__ModuleLoader__" packages/client/modules/src packages/client/web/src
  grep -Fq "expect(Object.keys(canvasClient).sort()).toEqual(['apply', 'inject'])" packages/client/ui-canvas/tests/rc8-contract.client.spec.ts
  grep -Fq "value: { revision: 0, entries: [] }" packages/client/ui-canvas/tests/client-bundle.client.spec.ts
  grep -Fq "当前状态：**BLOCKED / REVIEW**" .agents/workplans/canvas-v2.1/N11.5-rc8-compatibility.md
  echo "Renderer-root + validated overlay ownership assertions: PASS"
}

static_stage() {
  rm -rf /tmp/n11-5-overlay-static
  git worktree add --detach /tmp/n11-5-overlay-static "origin/$REPO_OVERLAY" >/tmp/worktree.log 2>&1
  (cd /tmp/n11-5-overlay-static && pnpm install --frozen-lockfile >/tmp/base-install.log 2>&1) || { tail -n 260 /tmp/base-install.log; exit 1; }

  set +e
  (cd /tmp/n11-5-overlay-static && pnpm run check:ci:static) >/tmp/base-static.log 2>&1
  base_static_status=$?
  pnpm run check:ci:static >/tmp/candidate-static.log 2>&1
  candidate_static_status=$?
  set -e

  BASE_STATUS="$base_static_status" CANDIDATE_STATUS="$candidate_static_status" python - <<'PY'
from pathlib import Path
import os, re
base_status = int(os.environ['BASE_STATUS'])
candidate_status = int(os.environ['CANDIDATE_STATUS'])
pattern = re.compile(r'^  - FAILED (.+?) \(', re.MULTILINE)
base_failed = set(pattern.findall(Path('/tmp/base-static.log').read_text(errors='replace')))
candidate_failed = set(pattern.findall(Path('/tmp/candidate-static.log').read_text(errors='replace')))
if candidate_status != 0 and not candidate_failed:
    raise SystemExit('renderer-root static failed without recognized failed-gate summary')
if candidate_status != 0 and base_status == 0:
    raise SystemExit('renderer-root static FAIL while exact validated overlay baseline PASS')
unexpected = candidate_failed - base_failed
if unexpected:
    raise SystemExit(f'renderer-root introduced new failing static gates beyond validated overlay baseline: {sorted(unexpected)}')
print(f'renderer-root full static failed-gate set is within validated overlay baseline: {sorted(candidate_failed)}')
PY

  gates=(
    constraints verify-package-invariants verify-package-paths verify-node-next-types
    verify-runtime-closure verify-optional-dependency-imports verify-cordis-config
    verify-cordis-catalog verify-client-catalog verify-client-domain-graph
    verify-export-jsdoc verify-config-catalog verify-doc-graphs
    verify-package-readme-model-experience verify-agent-note-classification
    verify-agent-note-format verify-type-equiv verify-translation-pairing
    verify-module-graph knip
  )
  for gate in "${gates[@]}"; do
    set +e
    (cd /tmp/n11-5-overlay-static && pnpm run "$gate") >"/tmp/base-$gate.log" 2>&1
    base_status=$?
    pnpm run "$gate" >"/tmp/candidate-$gate.log" 2>&1
    candidate_status=$?
    set -e
    BASE_STATUS="$base_status" CANDIDATE_STATUS="$candidate_status" GATE="$gate" python - <<'PY'
from collections import Counter
from pathlib import Path
import os, re
gate = os.environ['GATE']
base_status = int(os.environ['BASE_STATUS'])
candidate_status = int(os.environ['CANDIDATE_STATUS'])
ansi = re.compile(r'\x1b\[[0-9;]*m')
candidate_root = str(Path.cwd())
baseline_root = '/tmp/n11-5-overlay-static'
paren_location = re.compile(r'(\((?:packages|apps|scripts|docs|\.agents)/[^():]+):\d+(?::\d+)?\)')
prefix_location = re.compile(r'^((?:packages|apps|scripts|docs|\.agents)/[^:]+):(?: line )?\d+(?::\d+)?:')
def normalized(path: str) -> Counter[str]:
    out: Counter[str] = Counter()
    for raw in Path(path).read_text(errors='replace').splitlines():
        line = ansi.sub('', raw).strip()
        line = line.replace(candidate_root, '<ROOT>').replace(baseline_root, '<ROOT>')
        if not line:
            continue
        if line.startswith('> @deepseek-ai/dsh-root@') or line.startswith('$ '):
            continue
        if line.startswith('ELIFECYCLE') or line.startswith('ERR_PNPM'):
            continue
        if gate == 'verify-export-jsdoc' and re.fullmatch(r'verify-export-jsdoc: \d+ JSDoc completeness violation\(s\) \(see AGENTS\.md\):', line):
            continue
        line = paren_location.sub(lambda match: re.sub(r':\d+(?::\d+)?\)$', ':<LINE>)', match.group(0)), line)
        line = prefix_location.sub(lambda match: re.sub(r'(?:: line |:)\d+(?::\d+)?:$', ':<LINE>:', match.group(0)), line)
        out[line] += 1
    return out
base = normalized(f'/tmp/base-{gate}.log')
candidate = normalized(f'/tmp/candidate-{gate}.log')
if candidate_status == 0:
    print(f'{gate}: candidate PASS (baseline status {base_status})')
else:
    if base_status == 0:
        raise SystemExit(f'{gate}: renderer-root FAIL while validated overlay baseline PASS')
    unexpected = candidate - base
    if unexpected:
        print(f'=== {gate} overlay baseline ===')
        print(Path(f'/tmp/base-{gate}.log').read_text(errors='replace'))
        print(f'=== {gate} renderer-root candidate ===')
        print(Path(f'/tmp/candidate-{gate}.log').read_text(errors='replace'))
        raise SystemExit(f'{gate}: renderer-root introduced diagnostics beyond overlay baseline: {sorted(unexpected.elements())}')
    print(f'{gate}: no new diagnostics beyond overlay baseline ({sum(candidate.values())} candidate / {sum(base.values())} baseline normalized lines)')
PY
  done
  git worktree remove --force /tmp/n11-5-overlay-static
  echo "Renderer-root exact-overlay static diagnostic differential: PASS"
}

host_build_stage() {
  set -o pipefail
  pnpm run build:lib:host >/tmp/host-build.log 2>&1 || { tail -n 420 /tmp/host-build.log; exit 1; }
  echo "Host build: PASS"
}

client_build_stage() {
  set -o pipefail
  pnpm run build:lib:client >/tmp/client-build.log 2>&1 || { tail -n 420 /tmp/client-build.log; exit 1; }
  echo "Client build: PASS"
}

tests_stage() {
  set -o pipefail
  pnpm exec vitest run \
    packages/bundle/web-app/tests/renderer-root-ownership.spec.ts \
    packages/client/modules/tests/loader.client.spec.ts \
    packages/client/modules/tests/node-half.client.spec.ts \
    packages/client/ui-renderer/tests/app.client.spec.tsx \
    packages/client/ui-renderer/tests/document-title.client.spec.tsx \
    packages/client/ui-renderer/tests/ui-renderer.client.spec.tsx \
    packages/client/web/tests/boot-page.client.spec.ts \
    packages/client/web/tests/boot.client.spec.ts \
    packages/client/ui-canvas/tests/rc8-contract.client.spec.ts \
    packages/bundle/web-app/tests/canvas-client-ownership.spec.ts \
    packages/bundle/web-app/tests/canvas-roster.spec.ts \
    packages/client/ui-canvas/tests/adapters.client.spec.ts \
    packages/client/ui-canvas/tests/catalog.client.spec.ts \
    packages/client/ui-canvas/tests/editor-components.client.spec.tsx \
    packages/client/ui-canvas/tests/workflow-editor.client.spec.tsx \
    packages/client/ui-canvas/tests/layout-revision.client.spec.ts \
    packages/canvas/media-workflow/tests/registry.spec.ts \
    packages/canvas/media-workflow/tests/plugin-node.spec.ts \
    packages/canvas/canvas/tests/migration.spec.ts \
    packages/canvas/canvas/tests/features.spec.ts \
    packages/canvas/canvas/tests/feature-settings.spec.ts \
    packages/canvas/canvas/tests/interaction-features.spec.ts \
    packages/canvas/canvas/tests/interaction.spec.ts \
    packages/canvas/canvas/tests/interaction-bridge.spec.ts \
    packages/client/ui-canvas/tests/capability-gate.client.spec.ts \
    packages/client/ui-canvas/tests/settings.client.spec.tsx \
    packages/client/ui-canvas/tests/features.client.spec.tsx \
    packages/client/ui-canvas/tests/interaction.client.spec.ts \
    packages/client/ui-canvas/tests/client-bundle.client.spec.ts \
    packages/bundle/base/tests/canvas-real-composition.spec.ts >/tmp/renderer-tests.log 2>&1 || { tail -n 700 /tmp/renderer-tests.log; exit 1; }
  tail -n 340 /tmp/renderer-tests.log
}

invariants_stage() {
  set -o pipefail
  pnpm run verify-built-package-invariants >/tmp/invariants.log 2>&1 || { tail -n 360 /tmp/invariants.log; exit 1; }
  tail -n 160 /tmp/invariants.log
}

push_stage() {
  git push origin HEAD:"$REPO_RENDERER"
}

case "${1:-}" in
  merge) merge_stage ;;
  install) install_stage ;;
  pair-commit) pair_commit_stage ;;
  ownership) ownership_stage ;;
  static) static_stage ;;
  host-build) host_build_stage ;;
  client-build) client_build_stage ;;
  tests) tests_stage ;;
  invariants) invariants_stage ;;
  push) push_stage ;;
  *) echo "unknown stage: ${1:-}" >&2; exit 2 ;;
esac
