/** `canvas` namespace dictionaries for the session-native Canvas surface. */
export const NS = 'canvas'
export const zh = {
  'view.canvas':'画布','mode.minimal':'极简','mode.editor':'编辑','mode.aria':'画布模式','save.saved':'已保存','save.saving':'保存中','save.conflict':'存在冲突','save.offline':'离线','save.save-failed':'保存失败','projection.loading':'正在同步画布…','projection.layoutLoading':'正在同步画布布局…','projection.unavailable':'当前画布不可用或不可见。',
  'state.EMPTY.title':'开始创作','state.EMPTY.body':'在右侧输入框描述你想生成或修改的图片或视频。','state.READY.title':'工作流已就绪','state.READY.body':'当前工作流可以运行。','state.DIRTY_READY.title':'工作流有未运行的修改','state.DIRTY_READY.body':'正在保留上一次结果；重新运行后会生成与当前工作流一致的新结果。','state.RUNNING.title':'正在生成','state.RUNNING.body':'当前运行正在处理媒体工作流。','state.COMPLETED.title':'生成完成','state.COMPLETED.body':'结果来自当前工作流版本。','state.FAILED.title':'生成失败','state.FAILED.body':'本次运行未完成，可以重试。','state.CANCELLED.title':'已取消','state.CANCELLED.body':'本次运行已取消，可以重新生成。','state.INTERRUPTED.title':'运行被中断','state.INTERRUPTED.body':'Host 重启或运行恢复失败时会进入此状态，可以重试。',
  'action.run':'运行','action.retry':'重试','action.cancel':'取消','action.unavailable':'运行控制将在媒体执行能力接入后启用','minimal.output':'当前结果','minimal.emptyOutput':'还没有生成结果','asset.image':'图片结果','asset.video':'视频结果','asset.primary':'主要结果','feature.unavailable':'当前部署不可用','editor.noWorkflow':'当前没有工作流','editor.preparing':'正在切换到当前画布…','editor.catalogUnavailable':'节点目录暂不可用，已切换为极简模式。',
  'editor.library':'节点库','editor.libraryEmpty':'当前没有可创建的已安装节点。','editor.inspector':'检查器','editor.inspectorEmpty':'选择一个节点后编辑名称和配置。','editor.nodeName':'节点名称','editor.nodeConfig':'配置 JSON','editor.autosaveHint':'停止输入 450ms 或离开字段时保存。','editor.nodeDefinitionMissing':'当前 Host 未安装这个节点版本的定义，历史节点保持可见但不能编辑。','editor.nodeFeatureDisabled':'这个节点依赖的部署能力当前已关闭，历史节点保持可见但不能编辑。','editor.nodeReadOnly':'只读：不会向 Host 提交节点名称、配置或端口修改。','editor.validationOk':'配置有效','editor.validationIssue':'需要处理','editor.validationRevision':'工作流版本已变化，请先处理冲突。','editor.validationConflict':'该草稿基于旧版本，未自动覆盖最新工作流。',
  'editor.connections':'连接','editor.connectionSource':'输出端口','editor.connectionTarget':'输入端口','editor.connectionEmpty':'当前工作流没有可连接的输入/输出端口。','editor.connect':'建立连接',
  'editor.undo':'撤销','editor.redo':'重做','editor.copy':'复制','editor.paste':'粘贴','editor.delete':'删除','editor.shortcuts':'快捷键：⌘/Ctrl+A 全选，C/V 复制粘贴，Z 撤销，Shift+Z 重做，Delete 删除。','editor.commandEditNode':'编辑节点','editor.commandPaste':'粘贴节点','editor.commandDelete':'删除选择','editor.commandAddNode':'添加节点','editor.commandConnect':'连接节点','editor.copySuffix':'副本',
  'settings.nav':'画布','settings.title':'画布能力','settings.intro':'配置此部署下一次启动时提供的画布能力。当前正在运行的能力不会被这组开关即时改写。','settings.loading':'正在读取画布设置…','settings.unavailable':'当前连接无法编辑 Host 画布设置。','settings.readOnly':'当前设置存储为只读，无法修改。','settings.restartBadge':'重启生效','settings.restartNotice':'保存的修改会在 Host 下次启动或重新装载 Canvas 功能服务后生效。当前界面继续以 Host 已发布的实际能力为准。','settings.overridden':'已由用户设置覆盖','settings.inherited':'继承部署默认值','settings.reset':'恢复默认',
  'settings.feature.canvas.title':'画布','settings.feature.canvas.body':'启用画布产品面和画布操作；关闭后所有子能力在运行时都会视为不可用。',
  'settings.feature.editor.title':'工作流编辑器','settings.feature.editor.body':'启用可视化工作流编辑器和 Browser 编辑操作。',
  'settings.feature.history.title':'运行历史','settings.feature.history.body':'启用画布运行历史查询。',
  'settings.feature.video.title':'视频','settings.feature.video.body':'允许已安装的后续视频节点和执行能力被创建或使用。',
  'settings.feature.variants.title':'变体','settings.feature.variants.body':'为后续 Canvas Variant 操作开放部署能力。',
  'settings.feature.partialRun.title':'部分运行','settings.feature.partialRun.body':'为后续工作流局部执行开放部署能力。',
  'settings.feature.regionEdit.title':'区域编辑','settings.feature.regionEdit.body':'允许区域／蒙版交互以及后续局部编辑能力。',
  'settings.feature.providerFallback.title':'Provider 回退','settings.feature.providerFallback.body':'为后续 Provider fallback 运行策略开放部署能力。',
} as const
export const en: Record<CanvasKey,string> = {
  'view.canvas':'Canvas','mode.minimal':'Minimal','mode.editor':'Editor','mode.aria':'Canvas mode','save.saved':'Saved','save.saving':'Saving','save.conflict':'Conflict','save.offline':'Offline','save.save-failed':'Save failed','projection.loading':'Syncing Canvas…','projection.layoutLoading':'Syncing Canvas layout…','projection.unavailable':'Canvas is currently unavailable or hidden.',
  'state.EMPTY.title':'Start creating','state.EMPTY.body':'Describe the image or video you want to generate or edit in the composer on the right.','state.READY.title':'Workflow ready','state.READY.body':'The current workflow is ready to run.','state.DIRTY_READY.title':'Workflow has unrun changes','state.DIRTY_READY.body':'The previous result stays visible until you run the current workflow.','state.RUNNING.title':'Generating','state.RUNNING.body':'The current media workflow run is in progress.','state.COMPLETED.title':'Generation complete','state.COMPLETED.body':'The result matches the current workflow revision.','state.FAILED.title':'Generation failed','state.FAILED.body':'This run did not complete and can be retried.','state.CANCELLED.title':'Cancelled','state.CANCELLED.body':'This run was cancelled and can be generated again.','state.INTERRUPTED.title':'Run interrupted','state.INTERRUPTED.body':'A Host restart or failed recovery can interrupt a run; it can be retried.',
  'action.run':'Run','action.retry':'Retry','action.cancel':'Cancel','action.unavailable':'Run controls enable when media execution is connected','minimal.output':'Current result','minimal.emptyOutput':'No generated result yet','asset.image':'Image result','asset.video':'Video result','asset.primary':'Primary result','feature.unavailable':'Unavailable in this deployment','editor.noWorkflow':'No workflow yet','editor.preparing':'Switching to the current Canvas…','editor.catalogUnavailable':'The node catalog is unavailable; using Minimal mode.',
  'editor.library':'Node library','editor.libraryEmpty':'No installed node is currently creatable.','editor.inspector':'Inspector','editor.inspectorEmpty':'Select a node to edit its name and config.','editor.nodeName':'Node name','editor.nodeConfig':'Config JSON','editor.autosaveHint':'Saves 450ms after typing stops or when the field loses focus.','editor.nodeDefinitionMissing':'This exact node version is not installed on the current Host. Historical data remains visible but cannot be edited.','editor.nodeFeatureDisabled':'This node requires a deployment capability that is currently disabled. Historical data remains visible but cannot be edited.','editor.nodeReadOnly':'Read-only: no node name, config, or port mutation will be sent to the Host.','editor.validationOk':'Config valid','editor.validationIssue':'Needs attention','editor.validationRevision':'The workflow revision changed; resolve the conflict first.','editor.validationConflict':'This draft is based on an older revision and did not overwrite the latest workflow.',
  'editor.connections':'Connections','editor.connectionSource':'Output port','editor.connectionTarget':'Input port','editor.connectionEmpty':'This workflow has no connectable input/output ports.','editor.connect':'Connect',
  'editor.undo':'Undo','editor.redo':'Redo','editor.copy':'Copy','editor.paste':'Paste','editor.delete':'Delete','editor.shortcuts':'Shortcuts: ⌘/Ctrl+A select all, C/V copy/paste, Z undo, Shift+Z redo, Delete removes selection.','editor.commandEditNode':'Edit node','editor.commandPaste':'Paste nodes','editor.commandDelete':'Delete selection','editor.commandAddNode':'Add node','editor.commandConnect':'Connect nodes','editor.copySuffix':'copy',
  'settings.nav':'Canvas','settings.title':'Canvas capabilities','settings.intro':'Configure the Canvas capabilities this deployment will offer on its next activation. These switches do not rewrite the capabilities of the Host process already running.','settings.loading':'Loading Canvas settings…','settings.unavailable':'This connection cannot edit Host Canvas settings.','settings.readOnly':'The current settings provider is read-only.','settings.restartBadge':'Restart required','settings.restartNotice':'Saved changes take effect when the Host next starts or remounts the Canvas feature service. The current UI continues to follow the effective capabilities published by the running Host.','settings.overridden':'User override','settings.inherited':'Inherited deployment default','settings.reset':'Reset',
  'settings.feature.canvas.title':'Canvas','settings.feature.canvas.body':'Enable the Canvas product surface and Canvas operations. When off, every child capability is effectively disabled.','settings.feature.editor.title':'Workflow editor','settings.feature.editor.body':'Enable the visual workflow Editor and Browser editor mutations.','settings.feature.history.title':'Run history','settings.feature.history.body':'Enable Canvas run-history queries.','settings.feature.video.title':'Video','settings.feature.video.body':'Allow installed future video nodes and execution capabilities to be created or used.','settings.feature.variants.title':'Variants','settings.feature.variants.body':'Expose the deployment capability for future Canvas Variant operations.','settings.feature.partialRun.title':'Partial run','settings.feature.partialRun.body':'Expose the deployment capability for future partial workflow execution.','settings.feature.regionEdit.title':'Region editing','settings.feature.regionEdit.body':'Allow region/mask interaction and later local editing capabilities.','settings.feature.providerFallback.title':'Provider fallback','settings.feature.providerFallback.body':'Expose the deployment capability for future Provider fallback runtime policy.',
}
export type CanvasKey = keyof typeof zh